import {potArrangement} from '../app/arrangements.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createSession,clone,transaction,totals,undo,moveMoney} from '../app/core.mjs';
import {containerModel,containerNumber,ruleBenefitLinks,agreementCondition,agreementChangeEffects,removeContainerRule,attachedRules,saveContainerRule,previewRuleTrigger,executeRuleTrigger,evolveContainer,inviteToContainer,acceptContainerInvite} from '../app/container-model.mjs';
const root=new URL('../../Scenarios/',import.meta.url),data={moments:{},shared:{}};
for(const f of readdirSync(new URL('shared/',root)).filter(x=>x.endsWith('.json')))data.shared[f.slice(0,-5)]=JSON.parse(readFileSync(new URL('shared/'+f,root)));
for(const dir of readdirSync(new URL('moments/',root))){const l1=JSON.parse(readFileSync(new URL('moments/'+dir+'/l1.json',root))),l2=JSON.parse(readFileSync(new URL('moments/'+dir+'/l2.json',root)));data.moments[l1.customer.id]={l1,l2};}
const person=id=>createSession(data).people[id];
test('five variations share identity and amounts; wallet extension creates no money or schedules',()=>{for(const [id,key,type] of [['jordan','budget','budget'],['sam','house','savings'],['jordan','loan','loan'],['elena','inv','investment'],['elena','fam','savings']]){const p=person(id),x=p.l1.pots.find(x=>x.id===key),c=containerModel(p,x),m=containerNumber(p,x);assert.equal(c.type,type);assert.equal(m.containerId,key);assert.equal(m.action,'pot:'+key);assert.equal(c.amount,x.balance);}const p=person('jordan');assert.equal(p.l1.pots.find(x=>x.id==='budget').balance,0);assert.equal(totals(p).speed,222);});
test('actual contributions fulfil savings conditions regardless of automation',()=>{const p=person('sam'),x=p.l1.pots.find(x=>x.id==='house'),rate=containerModel(p,x).key;assert.equal(agreementCondition(p,x).received,0);assert.equal(agreementCondition(p,x).status,'Planned');p.l1.rules.find(r=>r.potId==='house').active=false;assert.equal(agreementCondition(p,x).status,'Your action');assert.equal(containerModel(p,x).key,rate);moveMoney(p,'ac-cur','house',320);assert.equal(agreementCondition(p,x).status,'Complete');assert.equal(agreementCondition(p,x).received,320);p.l1.autonomy.paused=true;assert.equal(agreementCondition(p,x).status,'Complete');assert.equal(containerModel(p,x).key,rate);});
test('fixed rule review is inert; execution respects protected balances, caps, ledger conservation and undo',()=>{const p=person('jordan'),d={type:'payday-fixed',source:'ac-cur',potId:'budget',amount:220,limitMonthly:220,reserve:500},net=totals(p).net;const r=saveContainerRule(p,d);assert.equal(p.l1.pots.find(x=>x.id==='budget').balance,0);assert.ok(attachedRules(p,'ac-cur').includes(r));assert.ok(attachedRules(p,'budget').includes(r));const before=clone(p.l1);assert.equal(previewRuleTrigger(p,r).amount,220);transaction(p,'Sample trigger',()=>executeRuleTrigger(p,r.id));assert.equal(totals(p).net,net);assert.equal(p.l1.transactions.length,before.transactions.length+2);assert.equal(previewRuleTrigger(p,r).amount,0);undo(p);assert.deepEqual(p.l1,before);r.reserve=2300;assert.equal(previewRuleTrigger(p,r).amount,0);});
test('variable rules never invent a fixed contribution; round-ups cannot overpay a debt',()=>{const p=person('jordan'),loan=p.l1.pots.find(x=>x.id==='loan');loan.balance=.25;const r=saveContainerRule(p,{type:'round-up',source:'ac-cur',potId:'loan',amount:0,limitMonthly:30,reserve:100});assert.equal(r.amount,0);assert.equal(previewRuleTrigger(p,r).amount,.25);const net=totals(p).net;executeRuleTrigger(p,r.id);assert.equal(loan.balance,0);assert.equal(totals(p).net,net);assert.equal(previewRuleTrigger(p,r).amount,0);});
test('sweeps respect the protected remainder, global pause and monthly cap',()=>{const p=person('sam'),r=saveContainerRule(p,{type:'payday-sweep',source:'ac-cur',potId:'un',amount:0,limitMonthly:150,reserve:3000});assert.equal(previewRuleTrigger(p,r).amount,120.44);p.l1.autonomy.paused=true;assert.equal(previewRuleTrigger(p,r).amount,0);p.l1.autonomy.paused=false;executeRuleTrigger(p,r.id);assert.equal(p.l1.accounts[0].balance,3000);assert.equal(previewRuleTrigger(p,r).amount,0);});
test('invalid rules reject self transfers, debt sources, external accounts and invalid caps',()=>{const p=person('jordan'),d={type:'payday-fixed',source:'ac-cur',potId:'budget',amount:50,limitMonthly:50,reserve:0};for(const override of [{potId:'ac-cur'},{source:'loan'},{source:'monzo/current'},{limitMonthly:10},{reserve:-1},{amount:NaN}])assert.throws(()=>saveContainerRule(p,{...d,...override}));});
test('savings evolution preserves ledger, amount and rule links; no shared or debt relabelling',()=>{const p=person('sam'),x=p.l1.pots.find(x=>x.id==='house'),before=clone(p.l1),net=totals(p).net;transaction(p,'Evolve',()=>evolveContainer(p,'house','investment'));assert.equal(x.id,'house');assert.equal(x.balance,6400);assert.equal(x.growthAnnual,.05);assert.equal(x.terms,null);assert.deepEqual(p.l1.rules,before.rules);assert.deepEqual(p.l1.transactions,before.transactions);assert.equal(totals(p).net,net);undo(p);assert.deepEqual(p.l1,before);assert.throws(()=>evolveContainer(person('jordan'),'loan','investment'));assert.throws(()=>evolveContainer(person('elena'),'fam','investment'));});
test('invitation has no sharing permission until explicit acceptance; undo restores privacy',()=>{const p=person('jordan'),x=p.l1.pots.find(x=>x.id==='budget'),r=inviteToContainer(p,x.id,'Taylor','View only');assert.equal(containerModel(p,x).shared,false);transaction(p,'Demo acceptance',()=>acceptContainerInvite(p,r.id));assert.equal(containerModel(p,x).shared,true);assert.equal(x.memberAccess[r.id].role,'View only');assert.throws(()=>acceptContainerInvite(p,r.id));undo(p);assert.equal(containerModel(p,p.l1.pots.find(x=>x.id==='budget')).shared,false);});
test('pausing loan automation keeps the instalment obligation and rate',()=>{const p=person('jordan'),x=p.l1.pots.find(x=>x.id==='loan');p.l1.rules.find(r=>r.potId==='loan').active=false;assert.equal(agreementCondition(p,x).required,150);assert.equal(agreementCondition(p,x).status,'Complete');p.l1.asOf='2026-10-01';assert.equal(agreementCondition(p,x).status,'Your action');assert.equal(containerModel(p,x).key,'0% fixed');moveMoney(p,'ac-cur','loan',150);assert.equal(agreementCondition(p,x).status,'Complete');});
test('editing an existing challenge retains its condition and cannot silently turn it into unconditional funding',()=>{const p=person('sam'),r=p.l1.rules.find(x=>x.type==='challenge'),condition=r.condition;saveContainerRule(p,{...r,amount:40,limitMonthly:40,reserve:200});assert.equal(r.condition,condition);assert.equal(r.amount,40);assert.throws(()=>saveContainerRule(p,{...r,type:'payday-fixed'}));assert.equal(previewRuleTrigger(p,r).amount,0);});

test('all container variants expose their economics and conditions through one model',()=>{for(const id of ['alex','jordan','sam','elena']){const p=person(id);for(const item of [...p.l1.pots,...p.l1.accounts]){const c=containerModel(p,item);assert.ok(c.arrangement);if(['savings','credit','loan'].includes(c.type))assert.match(c.key,/%/);if(c.type==='budget')assert.match(c.key,/cashback/);assert.ok(containerNumber(p,item).rows.some(r=>r[0]==='Your benefit'&&r[1]===c.key));}}});

test('money rules are fulfilment methods; choices, locks and capital are independent conditions',()=>{const sam=person('sam'),r=sam.l1.rules.find(r=>r.id==='r-house-payday');assert.equal(ruleBenefitLinks(sam,r)[0].required,false);const jordan=person('jordan');assert.deepEqual(potArrangement(jordan,jordan.l1.pots.find(x=>x.id==='budget')).conditions.map(c=>c.kind),['choice','payment','spending']);assert.equal(potArrangement(jordan,jordan.l1.pots.find(x=>x.id==='house')).conditions[0].kind,'lock');const elena=person('elena');assert.equal(potArrangement(elena,elena.l1.pots.find(x=>x.id==='inv')).conditions[0].kind,'capital');});
test('impact previews preserve evidence and separate scheduled from received money',()=>{const p=person('sam'),house=p.l1.pots.find(x=>x.id==='house');moveMoney(p,'ac-cur','house',100);const before=clone(p),effects=agreementChangeEffects(p,copy=>removeContainerRule(copy,'r-house-payday'));assert.equal(effects[0].after.received,100);assert.equal(effects[0].after.remaining,220);assert.equal(effects[0].after.scheduled,0);assert.deepEqual(p,before);saveContainerRule(p,{type:'payday-fixed',source:'ac-cur',potId:'house',amount:320,limitMonthly:320,reserve:0});assert.equal(agreementChangeEffects(p,copy=>removeContainerRule(copy,'r-house-payday'))[0].after.scheduled,320);p.l1.autonomy.paused=true;assert.equal(agreementCondition(p,house).received,100);assert.equal(agreementCondition(p,house).scheduled,0);});

test('a chosen lock blocks all withdrawals, outgoing rules and evolution until its end',()=>{const p=person('jordan'),x=p.l1.pots.find(x=>x.id==='house');x.arrangementState={lockedUntil:'2026-12-13'};assert.match(containerModel(p,x).key,/4.6%/);assert.throws(()=>moveMoney(p,'house','ac-cur',10),/locked/);assert.throws(()=>evolveContainer(p,'house','investment'),/lock/);const r=saveContainerRule(p,{type:'payday-fixed',source:'house',potId:'ef',amount:10,limitMonthly:10,reserve:0});assert.equal(previewRuleTrigger(p,r).amount,0);moveMoney(p,'ac-cur','house',10);assert.equal(x.balance,160);p.l1.asOf='2026-12-13';moveMoney(p,'house','ac-cur',10);assert.equal(x.balance,150);assert.match(containerModel(p,x).key,/4.0%/);});
test('payment evidence resets by month; capital monitoring cannot guarantee or silently reprice',()=>{const p=person('sam'),x=p.l1.pots.find(x=>x.id==='house');moveMoney(p,'ac-cur','house',320);assert.equal(agreementCondition(p,x).status,'Complete');p.l1.asOf='2026-10-01';assert.equal(agreementCondition(p,x).received,0);const e=person('elena'),inv=e.l1.pots.find(x=>x.id==='inv');inv.balance=90000;assert.equal(potArrangement(e,inv).conditions[0].status,'Below threshold');assert.equal(potArrangement(e,inv).benefit,'0.20%');});

test('household story variants are explicit money containers, and visible in My Numbers',()=>{
 const j=person('jordan'),s=person('sam');assert.equal(j.ui.order[0],'safespend');assert.equal(j.ui.sizes.safespend,'W');assert.ok(!j.ui.order.includes('grocery'));
 for(const id of ['grocery-wallet','social','flat']){assert.equal(containerModel(j,j.l1.pots.find(x=>x.id===id)).type,'budget');assert.ok(j.ui.order.includes('container-'+id));}
 for(const id of ['container-ac-cc','container-loan','efpot','safespend'])assert.ok(j.ui.order.includes(id));
 assert.equal(containerModel(j,j.l1.pots.find(x=>x.id==='flat')).shared,true);
 for(const id of ['family-budget','hol','ef'])assert.equal(containerModel(s,s.l1.pots.find(x=>x.id===id)).shared,true);
 assert.ok(!s.l1.pots.some(x=>x.members?.some(m=>(m.memberId||m)==='ella')));
});
test('missed agreement is dated evidence, not the presence of automation',()=>{
 const p=person('jordan'),x=p.l1.pots.find(x=>x.id==='grocery-wallet'),a=potArrangement(p,x);
 assert.equal(a.recovery.before,220);assert.equal(a.recovery.missing,100);assert.equal(a.benefit,'0% cashback');
 saveContainerRule(p,{source:'ac-cur',potId:x.id,type:'payday-fixed',amount:320,limitMonthly:320,reserve:0});
 assert.equal(potArrangement(p,x).recovery.ready,false);p.l1.autonomy.paused=true;assert.equal(potArrangement(p,x).benefit,'0% cashback');
 const net=totals(p).net;transaction(p,'Manual recovery payment',()=>moveMoney(p,'ac-cur',x.id,100));
 assert.equal(potArrangement(p,x).recovery.ready,true);assert.equal(potArrangement(p,x).benefit,'0% cashback');assert.equal(totals(p).net,net);
 p.l1.asOf='2026-10-01';assert.equal(potArrangement(p,x).benefit,'1% cashback');
 p.l1.asOf='2026-09-16';undo(p);assert.equal(potArrangement(p,p.l1.pots.find(item=>item.id==='grocery-wallet')).recovery.ready,false);
});
test('recovery respects date, merchant choice and spending; changing a limit cannot erase assessment',()=>{
 const p=person('jordan'),x=p.l1.pots.find(x=>x.id==='grocery-wallet');moveMoney(p,'ac-cur',x.id,100);delete x.arrangementState.merchant;assert.equal(potArrangement(p,x).recovery.ready,false);
 x.arrangementState.merchant='Tesco';p.l1.transactions.push({ledger:x.id,date:'2026-09-16',category:'groceries',amount:-200});x.budgetLimit=1000;assert.equal(potArrangement(p,x).recovery.ready,false);assert.equal(potArrangement(p,x).recovery.before,220);
 p.l1.asOf='2026-10-01';assert.equal(potArrangement(p,x).benefit,'0% cashback');
});
