import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createSession,clone,round,totals,valueAt,potRate,milestone,transaction,undo,applyIdea,previewPerson,moveMoney,completeQuiz,confirmBelief,redeem} from '../app/core.mjs';
import {moduleModel} from '../app/models.mjs';
const root=new URL('../../Scenarios/',import.meta.url), data={moments:{},shared:{modules:JSON.parse(readFileSync(new URL('shared/modules.json',root)))}};
for(const dir of readdirSync(new URL('moments/',root))){const l1=JSON.parse(readFileSync(new URL('moments/'+dir+'/l1.json',root))),l2=JSON.parse(readFileSync(new URL('moments/'+dir+'/l2.json',root)));data.moments[l1.customer.id]={l1,l2};}
const person=id=>createSession(data).people[id];
test('all four snapshots reconcile today without truncating target balances',()=>{for(const id of Object.keys(data.moments)){const p=person(id);for(const pot of p.l1.pots)assert.equal(valueAt(p,pot,0),pot.balance);assert.equal(round(totals(p).held-totals(p).owed),totals(p).net);for(const m of data.shared.modules.modules){const model=moduleModel(p,m.id,data.shared.modules);assert.ok(!JSON.stringify(model).includes('NaN'),id+' '+m.id);}}});
test('opening an investment preserves net worth and writes both ledger entries; undo is exact',()=>{const p=person('sam'),before=clone(p.l1),net=totals(p).net,w=p.l2.whatIfs.find(x=>x.id==='winvest');transaction(p,'Invest',()=>applyIdea(p,w));assert.equal(totals(p).net,net);assert.equal(p.l1.accounts[0].balance,1820.44);assert.equal(p.l1.transactions.length,before.transactions.length+2);assert.equal(totals(p).speed,620);undo(p);assert.deepEqual(p.l1,before);});
test('preview stacking never mutates live money, rules or receipts',()=>{const p=person('alex');p.ui.preview=['wef','whol'];const before=clone(p);const pp=previewPerson(p);assert.equal(pp.l1.pots.length,2);assert.equal(totals(pp).speed,75);assert.deepEqual(p,before);});
test('committing and undoing each supported idea for all moments',()=>{for(const id of Object.keys(data.moments))for(const w of data.moments[id].l2.whatIfs.filter(x=>x.canCommit)){const p=person(id),before=clone(p.l1);transaction(p,w.title,()=>applyIdea(p,w));assert.ok(p.ui.applied.includes(w.id));assert.throws(()=>transaction(p,'duplicate',()=>applyIdea(p,w)));undo(p);assert.deepEqual(p.l1,before,id+' '+w.id);assert.equal(p.ui.history.length,0);}});
test('redirecting £22 changes its destination without increasing money speed',()=>{const p=person('jordan'),speed=totals(p).speed;applyIdea(p,p.l2.whatIfs.find(x=>x.id==='wcc'));assert.equal(totals(p).speed,speed);assert.equal(potRate(p,p.l1.pots.find(x=>x.id==='ef')),50);assert.equal(potRate(p,p.l1.pots.find(x=>x.isDebt)),-172);});
test('insufficient funds rolls back pot creation and every state field',()=>{const p=person('sam');p.l1.accounts[0].balance=10;const before=clone(p);assert.throws(()=>transaction(p,'invest',()=>applyIdea(p,p.l2.whatIfs.find(x=>x.id==='winvest'))));assert.deepEqual(p,before);});
test('transfers conserve net worth, debt payments reduce both held and owed',()=>{const p=person('jordan'),net=totals(p).net;moveMoney(p,'ac-cur','ef',17.23);assert.equal(totals(p).net,net);moveMoney(p,'ac-cur','ac-cc',20);assert.equal(totals(p).net,net);assert.throws(()=>moveMoney(p,'ef','ef',1));assert.throws(()=>moveMoney(p,'ac-cur','ac-cc',1000));assert.throws(()=>moveMoney(p,'ac-cur','ef',NaN));assert.throws(()=>moveMoney(p,'ac-cur','ef',-1));});
test('global pause preserves individual choices and prevents projected contributions',()=>{const p=person('sam'),pot=p.l1.pots.find(x=>x.id==='ef');p.l1.rules[0].active=false;const flags=p.l1.rules.map(x=>x.active);p.l1.autonomy.paused=true;assert.equal(totals(p).speed,0);assert.equal(valueAt(p,pot,120),pot.balance);p.l1.autonomy.paused=false;assert.deepEqual(p.l1.rules.map(x=>x.active),flags);});
test('targets stop only where specified; debt never goes negative',()=>{const p=person('sam'),ef=p.l1.pots.find(x=>x.id==='ef'),house=p.l1.pots.find(x=>x.id==='house');assert.equal(valueAt(p,ef,120),5000);assert.ok(valueAt(p,house,120)>24000);assert.equal(valueAt(person('jordan'),person('jordan').l1.pots.find(x=>x.isDebt),120),0);});
test('future redirection starts after payoff and pauses with permissions',()=>{const p=person('sam'),ef=p.l1.pots.find(x=>x.id==='ef'),house=p.l1.pots.find(x=>x.id==='house');p.ui.redirects=[{from:'ef',to:'house'}];assert.equal(milestone(p,ef),20);assert.equal(valueAt(p,house,20),12800);assert.equal(valueAt(p,house,21),13160);p.l1.autonomy.paused=true;assert.equal(valueAt(p,house,40),6400);});
test('quiz uses answers and points cannot be farmed or awarded again to an existing customer',()=>{const a=person('alex'),b=person('alex');completeQuiz(a,[0,0,0]);completeQuiz(b,[2,1,2]);assert.notEqual(a.l2.personality.name,b.l2.personality.name);assert.equal(a.l1.rewards.points.balance,25);completeQuiz(a,[0,0,0]);assert.equal(a.l1.rewards.points.balance,25);const sam=person('sam'),points=sam.l1.rewards.points.balance;completeQuiz(sam,[1,1,1]);assert.equal(sam.l1.rewards.points.balance,points);});
test('belief correction preserves evidence and awards once',()=>{const p=person('jordan'),original=p.l2.beliefs[0].claim,n=p.l1.rewards.points.balance;confirmBelief(p,'belief-1','I shop for my household.');confirmBelief(p,'belief-1');assert.equal(p.l2.beliefs[0].previous,original);assert.equal(p.l1.rewards.points.balance,n+10);});
test('rewards enforce funds and tier; undo restores points and benefits',()=>{const p=person('sam'),before=clone(p.l1.rewards);assert.throws(()=>redeem(p,data.shared.modules.benefits.find(x=>x.id==='lounge')));transaction(p,'coach',()=>redeem(p,data.shared.modules.benefits.find(x=>x.id==='coach')));assert.equal(p.l1.rewards.points.balance,80);assert.throws(()=>redeem(p,data.shared.modules.benefits.find(x=>x.id==='coach')));undo(p);assert.deepEqual(p.l1.rewards,before);});
test('sequential undo restores complete prior data after dependent changes',()=>{const p=person('alex'),before=clone(p.l1);transaction(p,'quiz',()=>completeQuiz(p,[0,1,2]));transaction(p,'pot',()=>applyIdea(p,p.l2.whatIfs[0]));const pot=p.l1.pots[0];transaction(p,'transfer',()=>moveMoney(p,'ac-cur',pot.id,50));undo(p);assert.equal(p.l1.pots[0].balance,0);undo(p);assert.equal(p.l1.pots.length,0);assert.equal(p.l1.rewards.points.balance,25);undo(p);assert.deepEqual(p.l1,before);assert.equal(undo(p),false);});
test('Premier illustration can be previewed but cannot be committed',()=>{const p=person('sam'),w=p.l2.whatIfs.find(x=>x.id==='wprem');p.ui.preview=[w.id];assert.equal(totals(previewPerson(p)).speed,440);assert.equal(totals(p).speed,420);assert.throws(()=>transaction(p,'invalid commit',()=>applyIdea(p,w)));});
test('soft budget follows the chosen saving amount without altering recorded spending',()=>{const p=person('jordan'),spent=clone(p.l1.spending.byCategory);applyIdea(p,p.l2.whatIfs.find(x=>x.id==='weat'),30);assert.equal(p.l1.spending.softCaps['eating-out'],215);assert.deepEqual(p.l1.spending.byCategory,spent);});

test('grocery insight aggregates accounts and pots, excluding top-ups and other months',()=>{
 const p=person('jordan'),wallet=p.l1.pots.find(x=>x.id==='grocery-wallet');
 let m=moduleModel(p,'grocery',data.shared.modules);assert.equal(m.value,'£212.40');assert.equal(m.numberRole,'Spending insight');
 const potModel=moduleModel(p,'container-grocery-wallet',data.shared.modules);assert.equal(potModel.value,'£320');assert.equal(potModel.valueLabel,'Monthly budget');assert.equal(potModel.budget.spent,150.3);assert.equal(potModel.budget.available,69.7);assert.notEqual(m.action,potModel.action);
 moveMoney(p,'ac-cur',wallet.id,100);assert.equal(moduleModel(p,'grocery',data.shared.modules).value,'£212.40');assert.equal(wallet.balance,169.7);assert.equal(moduleModel(p,'container-grocery-wallet',data.shared.modules).budget.spent,150.3);
 p.l1.transactions.push({ledger:'ac-cc',date:p.l1.asOf,category:'groceries',amount:10,counterparty:'Tesco'});
 assert.equal(moduleModel(p,'grocery',data.shared.modules).value,'£222.40');
 p.l1.transactions.push({ledger:wallet.id,date:p.l1.asOf,category:'groceries',amount:5,counterparty:'Refund'});
 assert.equal(moduleModel(p,'grocery',data.shared.modules).value,'£217.40');
});
