import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
let JSDOM,VirtualConsole;try{({JSDOM,VirtualConsole}=require(process.env.ATLAS_JSDOM||'jsdom'));}catch{({JSDOM,VirtualConsole}=require('/Users/coy/ProductSweet/Portal/node_modules/jsdom'));}
function boot(edition='index',controlledClock=false){
 let now=0,next=0;const pending=new Map();
 const advance=ms=>{now+=ms;for(const [id,t] of [...pending])if(t.at<=now){pending.delete(id);t.fn();}};
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const html=readFileSync(new URL('../'+edition+'.html',import.meta.url),'utf8').replace(/<style>[\s\S]*?<\/style>/,'');
 const dom=new JSDOM(html,{url:'http://atlas.local/'+edition+'.html',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.CSS={escape:x=>x};if(controlledClock){w.setTimeout=(fn,ms=0)=>{const id=++next;pending.set(id,{fn,at:now+ms});return id;};w.clearTimeout=id=>pending.delete(id);}}}),w=dom.window,d=w.document;
 const click=a=>{let el=[...d.querySelectorAll('[data-action]')].find(x=>x.dataset.action===a&&!x.disabled);if(!el&&/^(condition-method|condition-pay|condition-merchant|condition-lock|container-agreement|agreement-recovery):/.test(a)){d.querySelector('[data-action^="container-how:"]')?.click();el=[...d.querySelectorAll('[data-action]')].find(x=>x.dataset.action===a&&!x.disabled);}assert.ok(el,'Missing enabled action: '+a);el.click();assert.equal(d.querySelector('#toast')?.textContent?.includes('undefined'),false);};
 return {dom,w,d,click,errors,advance,text:()=>d.body.textContent};
}
function how(b){if(!b.d.querySelector('.how-sheet'))b.d.querySelector('[data-action^="container-how:"]').click();return b.d.querySelector('.how-sheet');}
for(const edition of ['index','bento','metro','workbench'])test(edition+': four moments, all tabs, view modes, modules, stories and sheets render without exceptions',()=>{const b=boot(edition);for(const id of ['alex','jordan','sam','elena']){b.click('person:'+id);for(const tab of ['now','future','you']){b.click('tab:'+tab);assert.ok(!/undefined|NaN/.test(b.d.querySelector('#content').textContent),id+' '+tab);if(tab==='future'&&b.d.querySelector('.future-beginning'))b.click('future-studio');if(tab==='future')for(const v of ['rings','area','list','bubbles']){b.click('view:'+v);b.click('time:120');assert.ok(b.d.querySelector('#future-total').textContent.includes('£'));} }for(const action of ['collection','rules','points','chat','receipts','newplan','gallery']){b.w.atlas.closeAll();if(action==='gallery')b.w.atlas.sheetAdd();else if(action==='collection')b.w.atlas.collect();else if(action==='rules'){b.click('tab:future');b.click('rules');}else if(action==='points')b.w.atlas.sheetPoints();else if(action==='chat')b.w.atlas.convo();else if(action==='receipts'){b.click('tab:now');if(id==='elena')b.w.atlas.pin('activity');b.click('receipts');}else if(action==='newplan'){b.click('tab:future');b.click('newplan');}assert.ok(b.d.querySelector('[role=dialog]'));}b.w.atlas.closeAll();b.click('tab:now');const story=b.w.ATLAS_DATA.moments[id].l2.stories[0];b.click('story:'+story.id);b.click('story-step:1');b.click('story-step:2');b.w.atlas.closeAll();for(const m of b.w.ATLAS_DATA.shared.modules.modules){b.w.atlas.preview(m.id);assert.ok(!/undefined|NaN/.test(b.d.querySelector('.sheet').textContent),m.id);b.w.atlas.closeAll();}}assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('Alex quiz → confirm → points → undo uses real event wiring',()=>{const b=boot();b.click('support:discuss');b.click('quiz');b.click('answer:0');b.click('answer:1');b.click('answer:2');b.click('quiz-finish');assert.match(b.text(),/25/);b.click('portrait');b.click('personality-confirm');assert.match(b.text(),/35/);b.click('undo');assert.match(b.d.querySelector('.points-banner').textContent,/25/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('Jordan previews, commits a changed amount, transfers, and undoes',()=>{const b=boot();b.click('person:jordan');b.click('tab:future');b.click('idea:weat');b.click('toggle-idea:weat');assert.ok(b.d.querySelector('.preview-bar'));b.click('preview-summary');b.click('review-idea:weat');b.d.querySelector('#commit-amount').value='30';b.click('commit-idea:weat');assert.match(b.d.querySelector('.money-speed').textContent,/252/);b.w.atlas.collect();b.click('pot:ef');assert.match(b.d.querySelector('.detail-number').textContent,/430/);b.click('transfer-to:ef');b.d.querySelector('[name=amount]').value='20';b.click('transfer-review');b.click('transfer-confirm');b.w.atlas.detail('ef');assert.match(b.d.querySelector('.detail-number').textContent,/450/);b.w.atlas.closeAll();b.click('undo');b.w.atlas.detail('ef');assert.match(b.d.querySelector('.detail-number').textContent,/430/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('Sam investment review requires acknowledgement, then debits opening cash',()=>{const b=boot();b.click('person:sam');b.click('tab:future');b.click('idea:winvest');b.click('review-idea:winvest');b.click('commit-idea:winvest');assert.match(b.d.querySelector('#toast').textContent,/Review the illustrative plan/);b.d.querySelector('#advice-agreed').checked=true;b.click('commit-idea:winvest');b.w.atlas.collect();assert.match(b.d.querySelector('.sheet').textContent,/1,820.44/);assert.match(b.d.querySelector('.sheet').textContent,/First investments/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('Elena shared personality, beliefs, booking and permission pause',()=>{const b=boot();b.click('person:elena');b.click('tab:you');for(const m of ['aisha','leo','household']){b.click('member:'+m);assert.ok(!/undefined|NaN/.test(b.d.querySelector('.personality').textContent));}b.click('tab:now');b.click('support:discuss');b.click('appointment');b.click('book-appointment');b.click('tab:you');b.click('autonomy');b.click('pause-all');b.click('tab:future');assert.match(b.d.querySelector('.money-speed').textContent,/£0/);b.click('tab:you');b.click('autonomy');b.click('tab:future');assert.match(b.d.querySelector('.money-speed').textContent,/850/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('presentation API supports its scripted scenes and future zoom',()=>{const b=boot();const a=b.w.atlas;assert.doesNotThrow(()=>{a.closeAll();a.go('sam','now');a.go('sam','future');a.setT(24);a.detail('house');a.back();a.go('elena','now');a.rmReset();a.convo();a.closeAll();a.go('alex','now');a.unpin('safespend');a.sheetAdd();a.preview('safespend');a.pin('safespend','L');a.edit(true);a.edit(false);a.go('sam','future');a.wif('winvest');a.closeAll();a.go('sam','me');a.go('elena','me');a.sheetStatus();a.sheetPoints();a.closeAll();});b.click('tab:future');b.click('zoom:0.25');assert.equal(b.d.querySelector('.chart-viewport').style.width,'125%');b.click('zoom:fit');assert.equal(b.d.querySelector('.chart-viewport').style.width,'100%');assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('every rendered interactive control has an accessible name',()=>{const b=boot('bento');for(const id of ['alex','jordan','sam','elena']){b.click('person:'+id);for(const tab of ['now','future','you']){b.click('tab:'+tab);for(const el of b.d.querySelectorAll('button'))assert.ok(el.getAttribute('aria-label')||el.textContent.trim(),'Unnamed control '+el.outerHTML);}}b.dom.window.close();});
test('gallery uses a shared size preview, pins the chosen size and restores it on undo',()=>{const b=boot();b.click('gallery');b.click('preview-module:safespend');b.click('preview-size:T');assert.ok(b.d.querySelector('.module-preview .module.size-T'));b.click('pin-preview:safespend');assert.ok(b.d.querySelector('#content [data-module=safespend].size-T'));b.click('undo');assert.equal(b.d.querySelector('#content [data-module=safespend]'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('Future companion responds to time and a pot can enter the shared conversation',()=>{const b=boot();b.click('person:sam');b.click('tab:future');b.click('time:24');assert.match(b.d.querySelector('.ai-card').textContent,/milestone/i);b.w.atlas.detail('house');b.click('pot-chat:house');assert.match(b.d.querySelector('.chat-thread').textContent,/House deposit has £6,400.00/);assert.match(b.d.querySelector('.chat-thread').textContent,/£320/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('current, credit, saving, loan and investment share a container structure and contextual AI',()=>{const b=boot();for(const[person,action]of [['jordan','account:ac-cur'],['jordan','account:ac-cc'],['jordan','pot:ef'],['jordan','pot:loan'],['elena','pot:inv']]){b.click('person:'+person);b.w.atlas.collect();b.click(action);assert.deepEqual([...b.d.querySelectorAll('[data-container-section]')].map(x=>x.dataset.containerSection),['balance','actions','arrangement','activity']);assert.equal(b.d.querySelector('.pot-companion'),null);assert.ok(b.d.querySelector('#support-dock'));assert.ok(!/undefined|NaN/.test(b.d.querySelector('.container-detail').textContent));}b.click('person:jordan');b.w.atlas.collect();b.click('account:ac-cur');b.click('support:discuss');assert.match(b.d.querySelector('.chat-thread').textContent,/Safe to spend shows the estimate after those commitments/);b.w.atlas.closeAll();b.w.atlas.collect();b.click('account:ac-cc');b.click('transfer-to:ac-cc');assert.equal(b.d.querySelector('[name=to]').value,'ac-cc');assert.deepEqual(b.errors,[]);b.dom.window.close();});

function send(b,text){b.d.querySelector('#chat-input').value=text;b.d.querySelector('#chat-form').dispatchEvent(new b.w.Event('submit',{bubbles:true,cancelable:true}));}
function mockAudio(b){const stats={plays:0,pauses:0};b.w.HTMLMediaElement.prototype.play=function(){stats.plays++;Object.defineProperty(this,'paused',{value:false,configurable:true});this.dispatchEvent(new b.w.Event('play'));return Promise.resolve();};b.w.HTMLMediaElement.prototype.pause=function(){stats.pauses++;Object.defineProperty(this,'paused',{value:true,configurable:true});this.dispatchEvent(new b.w.Event('pause'));};return stats;}

test('one persistent support portal belongs to main/detail, and disappears during full-screen conversation',()=>{const b=boot();b.click('person:jordan');const dock=b.d.querySelector('#support-dock'),bar=dock.querySelector('.support-bar'),slot=dock.parentNode;b.w.atlas.detail('ef');const detail=b.d.querySelector('.sheet');assert.equal(dock.parentNode,slot);assert.equal(detail.firstElementChild.className,'sheet-header');assert.equal(detail.querySelector('#support-dock'),null);assert.equal(dock.hidden,false);assert.equal(dock.dataset.state,'compact');assert.equal(b.d.querySelector('#support-details').inert,true);assert.match(dock.textContent,/Emergency fund/);detail.querySelector('.sheet-body').scrollTop=42;b.d.querySelector('.support-bar').click();assert.match(b.d.querySelector('.chat-thread').textContent,/£570 to reach your £1,000 Emergency fund goal/);assert.equal(b.d.querySelector('.support-bar'),bar);assert.equal(dock.hidden,true);assert.equal(dock.inert,true);assert.ok(b.d.querySelector('.conversation-identity'));assert.equal(b.d.querySelector('#phone').getAttribute('aria-modal'),'true');b.click('close');assert.equal(b.d.querySelector('.sheet'),detail);assert.equal(detail.querySelector('.sheet-body').scrollTop,42);assert.equal(dock.hidden,false);assert.equal(dock.dataset.state,'compact');assert.equal(b.d.querySelector('#content').inert,true);b.click('close');assert.equal(b.d.querySelector('#content').inert,false);assert.equal(dock.parentNode,slot);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('scroll changes context without rebuilding controls, and page scrolling cannot replace an open conversation',async()=>{const b=boot(),content=b.d.querySelector('#content'),credit=b.d.querySelector('[data-module=creditscore]'),activity=b.d.querySelector('[data-module=activity]'),summary=b.d.querySelector('.support-summary');content.getBoundingClientRect=()=>({top:200,bottom:600,height:400});Object.defineProperty(content,'clientHeight',{value:400});let creditTop=220,activityTop=700;credit.getBoundingClientRect=()=>({top:creditTop,bottom:creditTop+160,height:160});activity.getBoundingClientRect=()=>({top:activityTop,bottom:activityTop+220,height:220});content.scrollTop=90;content.dispatchEvent(new b.w.Event('scroll'));await new Promise(r=>setTimeout(r,170));assert.ok(b.d.querySelector('#support-dock').classList.contains('is-compact'));assert.match(summary.textContent,/soft check/);assert.equal(summary,b.d.querySelector('.support-summary'));creditTop=-50;activityTop=220;content.dispatchEvent(new b.w.Event('scroll'));await new Promise(r=>setTimeout(r,170));assert.match(summary.textContent,/Every change/);b.click('support:discuss');assert.match(b.d.querySelector('.chat-thread').textContent,/recorded transactions/);const chatTitle=summary.textContent;content.scrollTop=0;content.dispatchEvent(new b.w.Event('scroll'));await new Promise(r=>setTimeout(r,170));assert.equal(summary.textContent,chatTitle);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('bar text opens AI even for Priya’s note, while only Premier exposes direct human access',()=>{const b=boot();for(const id of ['alex','jordan','sam']){b.click('person:'+id);b.click('support:discuss');assert.equal(b.d.querySelector('[data-action=human]'),null);assert.ok(b.d.querySelector('.chat-message:last-child').classList.contains('ai'));}b.click('person:elena');assert.match(b.d.querySelector('.support-summary').textContent,/Priya/);b.click('support:discuss');assert.match(b.d.querySelector('.chat-message.human').textContent,/Priya.*quarterly review/s);assert.ok(b.d.querySelector('.chat-message.human [data-author=priya] img'));assert.ok(b.d.querySelector('.chat-message:last-child').classList.contains('ai'));b.click('human');assert.ok(b.d.querySelector('.conversation-identity [data-author=priya] img'));send(b,'Tell me about my plans');assert.ok(b.d.querySelector('.chat-message:last-child').classList.contains('human'));b.click('support:ai');assert.ok(b.d.querySelector('.chat-message:last-child').classList.contains('ai'));assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('play avatar starts persistent bottom audio; scroll collapses support without interrupting playback',()=>{const b=boot(),stats=mockAudio(b);b.click('person:sam');assert.equal(b.d.querySelector('audio'),null);b.click('support:play');const media=b.d.querySelector('audio'),avatar=b.d.querySelector('.support-avatar'),range=b.d.querySelector('#recap-progress');assert.equal(stats.plays,1);assert.equal(b.d.querySelector('#audio-dock').hidden,false);assert.equal(b.d.querySelector('#support-dock .recap-player'),null);media.currentTime=17;media.dispatchEvent(new b.w.Event('timeupdate'));assert.equal(range,b.d.querySelector('#recap-progress'));b.d.querySelector('#content').dispatchEvent(new b.w.Event('wheel'));assert.ok(b.d.querySelector('#support-dock').classList.contains('is-compact'));assert.equal(b.d.querySelector('#support-details').inert,true);assert.equal(media.paused,false);b.click('support:play');assert.equal(stats.pauses,1);assert.ok(b.d.querySelector('#support-dock').classList.contains('is-compact'));assert.equal(b.d.querySelector('.support-avatar'),avatar);b.click('support:play');b.click('tab:future');assert.equal(b.d.querySelector('audio'),media);assert.equal(media.currentTime,17);b.click('support:back');assert.equal(media.currentTime,7);b.click('person:elena');assert.equal(stats.pauses,2);assert.equal(b.d.querySelector('audio'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('support follows story steps, idea review and a household selection',()=>{const b=boot();b.click('person:sam');b.click('story:s1');assert.match(b.d.querySelector('.support-summary').textContent,/Golden Ratio.*idea/);b.click('story-step:1');assert.match(b.d.querySelector('.support-summary').textContent,/Golden Ratio.*working/);b.click('close');b.click('tab:future');b.click('idea:winvest');assert.match(b.d.querySelector('.support-summary').textContent,/Exploring: Start investing/);b.click('person:elena');b.click('tab:you');b.click('member:aisha');assert.match(b.d.querySelector('.support-summary').textContent,/Aisha/);b.click('support:discuss');assert.match(b.d.querySelector('.chat-thread').textContent,/consent/);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('AI triages a non-Premier request before human handover; audio failure keeps the icon transcript route',()=>{const b=boot();mockAudio(b);b.click('person:jordan');b.w.atlas.detail('ef');b.click('support:discuss');send(b,'I would like a person');assert.equal(b.d.querySelector('.chat-message.human'),null);assert.match(b.d.querySelector('.chat-message:last-child').textContent,/What would you like help/);send(b,'My emergency fund contributions');assert.match(b.d.querySelector('.chat-thread').textContent,/context we were exploring: £570/);assert.match(b.d.querySelector('.support-summary').textContent,/Maya/);b.click('person:sam');b.click('support:play');b.d.querySelector('audio').dispatchEvent(new b.w.Event('error'));assert.match(b.d.querySelector('.recap-player').textContent,/Audio unavailable/);b.click('support:transcript');assert.match(b.d.querySelector('.sheet-body').textContent,/Hi Sam/);assert.equal(b.d.querySelector('.recap-snapshot'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('system workbench and blueprint expose the same production review states',()=>{for(const edition of ['workbench','support-blueprint']){const b=boot(edition);mockAudio(b);for(const state of ['expanded','compact','detail','conversation','priya','maya','audio','playing','detached','paused','ended','error']){b.click('support-case:'+state);assert.ok(b.d.querySelector('#support-diagnostics').textContent.includes('header'));assert.equal(b.d.querySelectorAll('#support-dock').length,1);if(state==='priya'){assert.equal(b.d.querySelectorAll('.support-actions button').length,2);assert.ok(b.d.querySelector('.support-avatar img').src.startsWith('data:image/jpeg;base64,'));}if(state==='maya'){assert.ok(b.d.querySelector('.conversation-identity [data-author=maya] img'));assert.match(b.d.querySelector('#support-diagnostics').textContent,/Maya/);}if(state==='error'){assert.match(b.d.querySelector('.recap-error').textContent,/unavailable/);b.click('support:transcript');assert.match(b.d.querySelector('.sheet-body').textContent,/Hi Sam/);}}assert.deepEqual(b.errors,[]);b.dom.window.close();}});
test('expanded CTAs hide on attention to content; conversation uses a consistent vendored AI identity',()=>{const b=boot('index',true);b.advance(2000);const details=b.d.querySelector('#support-details');assert.equal(details.inert,false);assert.ok(details.querySelector('[data-action=quiz]'));b.d.querySelector('#content').dispatchEvent(new b.w.Event('wheel'));assert.equal(details.inert,true);b.click('support:discuss');assert.equal(b.d.querySelector('#support-dock').hidden,true);for(const el of b.d.querySelectorAll('[data-author=ai] svg'))assert.equal(el.dataset.material,'auto_awesome');assert.ok(b.d.querySelector('.conversation-identity'));assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('details start compact without audio offers; ongoing audio stays in its independent player',()=>{const b=boot();mockAudio(b);b.click('person:sam');b.click('support:play');const audio=b.d.querySelector('audio');b.click('module:grocery');assert.equal(audio.paused,false);assert.equal(b.d.querySelector('#audio-dock').hidden,false);assert.equal(b.d.querySelector('.support-avatar').dataset.action,'support:discuss');assert.equal(b.d.querySelector('#support-dock').dataset.state,'compact');assert.match(b.d.querySelector('.support-message').textContent,/spent on groceries/);b.click('support:play');assert.equal(audio.paused,true);b.click('support:stop');assert.equal(b.d.querySelector('#audio-dock').hidden,true);assert.equal(b.d.querySelector('audio'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('main headers scroll away and top restores initial support on all three tabs; details stay fixed',()=>{const b=boot();for(const tab of ['now','future','you']){b.click('tab:'+tab);assert.equal(b.d.querySelector('.app-header [data-action="support:discuss"]'),null);const content=b.d.querySelector('#content'),phone=b.d.querySelector('#phone');content.scrollTop=120;content.dispatchEvent(new b.w.Event('scroll'));assert.equal(phone.style.getPropertyValue('--header-scroll'),'58px');assert.equal(b.d.querySelector('.app-header').inert,true);assert.equal(b.d.querySelector('#support-dock').dataset.state,'compact');content.scrollTop=0;content.dispatchEvent(new b.w.Event('scroll'));assert.equal(phone.style.getPropertyValue('--header-scroll'),'0px');assert.equal(b.d.querySelector('.app-header').inert,false);assert.equal(b.d.querySelector('#support-dock').dataset.state,tab==='you'?'compact':'expanded');assert.equal(b.d.querySelector('#support-details').inert,tab==='you');}b.click('tab:now');b.w.atlas.preview('grocery');const detail=b.d.querySelector('.sheet-body');detail.scrollTop=120;detail.dispatchEvent(new b.w.Event('scroll'));assert.equal(b.d.querySelector('#phone').style.getPropertyValue('--header-scroll'),'0px');detail.scrollTop=0;detail.dispatchEvent(new b.w.Event('scroll'));assert.equal(b.d.querySelector('#support-dock').dataset.state,'compact');assert.ok(b.d.querySelector('.sheet-header'));assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('trailing upward wheel and touch-end events cannot leave the top card minimised',async()=>{const b=boot(),content=b.d.querySelector('#content');content.scrollTop=130;content.dispatchEvent(new b.w.Event('scroll'));content.scrollTop=0;content.dispatchEvent(new b.w.Event('scroll'));for(let i=0;i<3;i++)content.dispatchEvent(new b.w.WheelEvent('wheel',{deltaY:-25}));assert.equal(b.d.querySelector('#support-dock').dataset.state,'expanded');content.dispatchEvent(new b.w.Event('touchmove'));content.dispatchEvent(new b.w.Event('touchend'));await new Promise(r=>setTimeout(r,150));assert.equal(b.d.querySelector('#support-dock').dataset.state,'expanded');assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('audio is offered only by the Now summary; contextual chat actions share the quick-response group',()=>{const b=boot('index',true);b.click('person:sam');b.advance(2000);assert.equal(b.d.querySelector('.support-avatar').dataset.action,'support:play');for(const tab of ['future','you']){b.click('tab:'+tab);assert.equal(b.d.querySelector('.support-avatar').dataset.action,'support:discuss');assert.equal(b.d.querySelector('audio'),null);}b.click('person:alex');b.click('support:discuss');assert.ok(b.d.querySelector('.chat-chips [data-action=quiz]'));assert.equal(b.d.querySelector('.chat-context-actions .btn'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('Now thinking lasts two seconds, yields to intent, and never leaks into other screens',()=>{
 const b=boot('index',true),state=()=>b.d.querySelector('#support-dock').dataset.state;
 assert.equal(state(),'thinking');assert.equal(b.d.querySelector('#support-details').inert,true);
 b.advance(1999);assert.equal(state(),'thinking');b.advance(1);assert.equal(state(),'expanded');assert.equal(b.d.querySelector('#support-details').inert,false);
 b.click('person:sam');assert.equal(state(),'thinking');assert.equal(b.d.querySelector('.support-avatar').dataset.action,'support:discuss');b.advance(2000);assert.equal(b.d.querySelector('.support-avatar').dataset.action,'support:play');
 b.click('tab:future');assert.equal(state(),'expanded');b.click('tab:now');assert.equal(state(),'thinking');b.click('tab:you');b.advance(2500);assert.equal(state(),'compact');assert.doesNotMatch(b.d.querySelector('.support-summary').textContent,/Thinking/);
 b.click('tab:now');assert.equal(state(),'thinking');const content=b.d.querySelector('#content');content.scrollTop=130;content.dispatchEvent(new b.w.Event('scroll'));assert.equal(state(),'compact');b.advance(2500);assert.equal(state(),'compact');content.scrollTop=0;content.dispatchEvent(new b.w.Event('scroll'));assert.equal(state(),'expanded');
 b.click('reset');assert.equal(state(),'thinking');b.click('support:discuss');b.advance(2500);assert.equal(b.d.querySelector('#support-dock').hidden,true);assert.doesNotMatch(b.d.querySelector('.chat-thread').textContent,/Thinking/);
 b.click('close');b.click('reset');b.click('module:grocery');b.advance(2500);assert.equal(state(),'compact');
 b.click('person:elena');assert.equal(state(),'expanded');assert.ok(b.d.querySelector('.support-avatar img'));assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('journey CTA owns its header; AI help preserves quiz step and form drafts',()=>{
 const b=boot('index',true);b.advance(2000);
 b.d.querySelector('.support-actions [data-action=quiz]').click();
 const journey=()=>{assert.equal(b.d.querySelector('#phone').dataset.supportSurface,'journey');assert.equal(b.d.querySelector('#support-dock').hidden,true);assert.ok(b.d.querySelector('.sheet-header .journey-help'));assert.ok(b.d.querySelector('.sheet.support-journey'));};
 journey();assert.match(b.d.querySelector('.sheet-header').textContent,/Getting to know you/);
 b.click('answer:0');const question=b.d.querySelector('.quiz-question').textContent,step=b.d.querySelector('.sheet-body');step.scrollTop=55;
 b.d.querySelector('.journey-help').click();assert.match(b.d.querySelector('.chat-thread').textContent,/question 2/);assert.ok(b.d.querySelector('.chat-thread').textContent.includes(question));b.click('close');journey();assert.equal(b.d.querySelector('.sheet-body'),step);assert.equal(step.scrollTop,55);assert.equal(b.d.querySelector('.quiz-question').textContent,question);assert.equal(b.d.activeElement,b.d.querySelector('.journey-help'));
 b.click('answer:1');b.click('answer:2');journey();assert.ok(b.d.querySelector('[data-action=quiz-finish]'));b.click('quiz-finish');assert.equal(b.d.querySelector('#phone').dataset.supportSurface,'main');
 b.click('tab:now');b.click('transfer');journey();const form=b.d.querySelector('#transfer-form'),amount=form.querySelector('[name=amount]');amount.value='12';b.d.querySelector('.journey-help').click();b.click('close');journey();assert.equal(b.d.querySelector('#transfer-form'),form);assert.equal(amount.value,'12');
 b.click('close');b.click('person:jordan');b.w.atlas.pin('grocery');b.click('module:grocery');assert.equal(b.d.querySelector('#phone').dataset.supportSurface,'detail');assert.equal(b.d.querySelector('#support-dock').hidden,false);assert.equal(b.d.querySelector('.journey-help'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('Now numbers share one grid; first number can resize, move, remove and be restored',()=>{
 const b=boot();assert.equal(b.d.querySelector('.lead-number'),null);assert.match(b.d.querySelector('.now-page').textContent,/My numbers/);
 const nodes=[...b.d.querySelector('.now-page').children];assert.ok(nodes.findIndex(n=>n.matches('.quick-actions'))<nodes.findIndex(n=>n.matches('.pots-entry')));assert.ok(nodes.findIndex(n=>n.matches('.module-grid'))<nodes.findIndex(n=>n.matches('.pots-entry')));assert.ok(nodes.findIndex(n=>n.matches('.pots-entry'))<nodes.findIndex(n=>n.matches('.stories')));assert.ok(nodes.findIndex(n=>n.matches('.stories'))<nodes.findIndex(n=>n.matches('.products-entry')));
 assert.ok(b.d.querySelector('.module-grid [data-module=container-ac-cur].size-W'));b.click('customise');b.click('size:container-ac-cur');assert.ok(b.d.querySelector('.module-grid [data-module=container-ac-cur].size-T'));b.click('up:dd');assert.equal(b.d.querySelector('.module-grid [data-module]').dataset.module,'dd');b.click('remove:container-ac-cur');assert.equal(b.d.querySelector('.module-grid [data-module=container-ac-cur]'),null);b.click('undo');assert.ok(b.d.querySelector('.module-grid [data-module=container-ac-cur].size-T'));assert.deepEqual(b.errors,[]);b.dom.window.close();
});
test('shortcut editor saves replacements, supports removal, cancellation, per-person preferences and undo',()=>{
 const b=boot();const primary=()=>[...b.d.querySelectorAll('#content .quick-actions button')].map(x=>x.textContent.trim());
 b.click('quick-more');b.click('quick-edit');b.click('quick-select:statements');b.click('quick-select:pay');b.click('quick-done');assert.deepEqual(primary(),['Statements','Transfer','Add money','More']);
 b.click('quick-more');b.click('quick-edit');b.click('quick-select:transfer');b.click('quick-place:available');assert.equal(b.d.querySelectorAll('.primary-actions [data-shortcut]').length,2);b.click('close');assert.deepEqual(primary(),['Statements','Transfer','Add money','More']);
 b.click('person:sam');assert.deepEqual(primary(),['Pay','Transfer','Add money','More']);b.click('person:alex');assert.equal(primary()[0],'Statements');b.click('receipts');b.click('undo');assert.equal(primary()[0],'Pay');assert.deepEqual(b.errors,[]);b.dom.window.close();
});
test('More actions and products open usable local screens and preserve catalogue return paths',()=>{
 const b=boot();b.click('quick-more');b.click('statements');b.click('statement:ac-cur');assert.match(b.d.querySelector('.sheet-body').textContent,/Acme Ltd/);b.click('close');assert.equal(b.d.querySelector('#dialog-title').textContent,'Statements');b.click('close');assert.equal(b.d.querySelector('#dialog-title').textContent,'Quick actions');
 b.click('cards');assert.equal(b.d.querySelectorAll('.bank-card').length,1);b.click('card-freeze:ac-cur');assert.match(b.d.querySelector('.card-state').textContent,/Frozen/);b.click('close');b.click('convert');b.d.querySelector('#convert-amount').value='200';b.d.querySelector('#convert-amount').dispatchEvent(new b.w.Event('input',{bubbles:true}));assert.equal(b.d.querySelector('#convert-result').textContent,'€234.00');b.w.atlas.closeAll();
 b.click('products');assert.equal(b.d.querySelectorAll('.products-grid button').length,10);b.click('product:savings');b.click('close');assert.equal(b.d.querySelector('#dialog-title').textContent,'Products and services');b.click('product:credit');b.click('products');b.click('close');assert.equal(b.d.querySelector('.sheet'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();
});


test('accounts collection connects chosen sample accounts, reconciles its count and disconnects without changing HSBC money',()=>{
 const b=boot();const count=()=>b.d.querySelector('.pots-entry').textContent;const beforeCount=Number(count().match(/\d+/)[0]);const beforeBalance=b.d.querySelector('[data-module=container-ac-cur] .module-value').textContent;
 b.click('collection');assert.match(b.d.querySelector('.support-message').textContent,/Connect accounts/);assert.ok(b.d.querySelector('.connect-entry [data-action=connect-bank]'));
 b.click('connect-bank');assert.equal(b.d.querySelector('#support-dock').hidden,true);b.click('connect-review:monzo');b.click('connect-confirm:monzo');assert.equal(b.d.querySelector('#connection-error').hidden,false);b.d.querySelector('#connection-form input[value=current]').checked=true;b.click('connect-confirm:monzo');
 assert.equal(Number(count().match(/\d+/)[0]),beforeCount+1);assert.equal(b.d.querySelectorAll('.other-banks .holding-row').length,1);assert.equal(b.d.querySelector('[data-module=container-ac-cur] .module-value').textContent,beforeBalance);assert.match(b.d.querySelector('.overview-footnote').textContent,/845.60/);assert.match(b.d.querySelector('.support-message').textContent,/845.60/);
 b.click('connected-account:monzo/current');b.click('disconnect-review:monzo');b.click('disconnect-confirm:monzo');assert.equal(Number(count().match(/\d+/)[0]),beforeCount);assert.equal(b.d.querySelectorAll('.other-banks .holding-row').length,0);assert.equal(b.d.querySelector('[data-module=container-ac-cur] .module-value').textContent,beforeBalance);b.click('undo');assert.equal(Number(count().match(/\d+/)[0]),beforeCount+1);assert.deepEqual(b.errors,[]);b.dom.window.close();
});
test('Open Banking consent stays a draft when cancelled; collection details restore their parent',()=>{
 const b=boot();b.click('collection');const body=b.d.querySelector('.sheet-body');body.scrollTop=150;b.click('account:ac-cur');b.click('close');assert.equal(b.d.querySelector('.sheet-body'),body);assert.equal(body.scrollTop,150);
 b.click('connect-bank');b.click('connect-review:starling');b.d.querySelector('#connection-form input').checked=true;b.click('close');assert.equal(b.d.querySelector('#dialog-title').textContent,'Connect another bank');b.click('close');assert.equal(b.d.querySelector('#dialog-title').textContent,'Accounts & pots');assert.equal(b.d.querySelectorAll('.other-banks .holding-row').length,0);assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('Sam and Elena start with distinct connected banks and reset restores their sample picture',()=>{
 const b=boot();for(const [person,count,external,total] of [['sam',12,2,'£100,345.60'],['elena',9,3,'£307,701.05']]){
 b.click('person:'+person);assert.match(b.d.querySelector('.pots-entry').textContent,new RegExp('· '+count));b.click('collection');assert.equal(b.d.querySelectorAll('.other-banks .holding-row').length,external);assert.equal(b.d.querySelector('.overview-value').textContent,total);assert.ok(b.d.querySelector('[data-bank=hsbc] img').src.startsWith('data:image/'));for(const img of b.d.querySelectorAll('.other-banks .bank-avatar img'))assert.ok(img.src.startsWith('data:image/'));
 const bank=person==='sam'?'monzo':'natwest';b.click('connected-account:'+bank+'/current');b.click('disconnect-review:'+bank);b.click('disconnect-confirm:'+bank);b.click('connect-bank');b.click('connect-review:'+bank);assert.match(b.d.querySelector('.consent-accounts').textContent,person==='sam'?/845.60/:/3,840.80/);b.w.atlas.closeAll();b.click('reset');b.click('collection');assert.equal(b.d.querySelector('.overview-value').textContent,total);b.w.atlas.closeAll();
 }assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('five container variants follow the supplied IA; wallet rules require review and update the same Number',()=>{const b=boot('workbench');for(const id of ['budget','savings','loan','investment','shared']){b.click('bench-container:'+id);assert.deepEqual([...b.d.querySelectorAll('[data-container-section]')].map(x=>x.dataset.containerSection),['balance','actions','arrangement','activity']);assert.equal(b.d.querySelector('.sheet-header').textContent.includes('undefined'),false);assert.equal(b.d.querySelector('#support-dock').dataset.state,'compact');assert.equal(b.d.querySelectorAll('.container-system').length,1);assert.ok(!/undefined|NaN|\[object Object\]/.test(b.d.querySelector('.container-system').textContent));}b.click('bench-container:budget');b.click('container-more:budget');b.click('container-rule-new:budget');assert.equal(b.d.querySelector('#support-dock').hidden,true);b.d.querySelector('[name=amount]').value='220';b.d.querySelector('[name=limitMonthly]').value='220';b.d.querySelector('[name=reserve]').value='500';b.click('container-rule-review:budget');assert.match(b.d.querySelector('.sheet-body').textContent,/Money moved now£0/);b.click('container-rule-save');b.click('condition-method:budget/funding');assert.equal(b.d.querySelectorAll('.container-rule').length,1);const rule=b.d.querySelector('.container-rule').dataset.action;b.click(rule);b.click(rule.replace('container-rule:','container-rule-toggle:'));b.click('container-rule-confirm');b.click('condition-method:budget/funding');assert.match(b.d.querySelector('.container-rule .status-chip').textContent,/Paused/);b.w.atlas.closeAll();b.w.atlas.detail('budget');b.click('container-info:budget');b.click('preview-module:container-budget');b.click('preview-size:W');b.click('pin-preview:container-budget');assert.ok(b.d.querySelector('#content [data-module=container-budget].size-W'));assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('editing a payment changes fulfilment while cancellation and rate are preserved',()=>{const b=boot('workbench');b.click('bench-container:savings');b.click('condition-method:house/contribution');b.click('container-rule:r-house-payday');b.click('container-rule-edit:r-house-payday');b.d.querySelector('[name=amount]').value='100';b.click('container-rule-review:house');assert.match(b.d.querySelector('.method-overview').textContent,/£220.*manually/);b.click('close');b.w.atlas.closeAll();b.w.atlas.detail('house');assert.match(how(b).querySelector('[data-condition=contribution]').textContent,/Planned/);b.click('condition-method:house/contribution');b.click('container-rule:r-house-payday');b.click('container-rule-edit:r-house-payday');b.d.querySelector('[name=amount]').value='100';b.click('container-rule-review:house');b.click('container-rule-save');assert.match(how(b).querySelector('[data-condition=contribution]').textContent,/£220.*yourself/);assert.match(b.d.querySelector('.arrangement-benefit').textContent,/5.1%/);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('sharing waits for explicit demo acceptance; evolution keeps amount, identity, and updates the widget',()=>{const b=boot('workbench');b.click('bench-container:budget');b.click('container-more:budget');b.click('container-members:budget');b.d.querySelector('#container-invite-form [name=name]').value='Taylor';b.click('container-invite-review:budget');b.click('container-invite-save');assert.match(b.d.querySelector('.container-invitation').textContent,/waiting for acceptance/);b.click('container-accept:invite-0');assert.match(b.d.querySelector('.container-members').textContent,/Taylor/);b.click('bench-container:savings');b.click('container-more:house');b.click('container-evolve:house');b.click('container-evolve-confirm:house');assert.ok(b.d.querySelector('#container-risk-agreed'));b.d.querySelector('#container-risk-agreed').checked=true;b.click('container-evolve-confirm:house');assert.equal(b.d.querySelector('.container-system').dataset.containerType,'investment');assert.match(b.d.querySelector('.detail-number').textContent,/6,400/);assert.match(b.d.querySelector('#content [data-module=housepot]').textContent,/fall/);assert.equal(how(b).querySelectorAll('.container-rule').length,1);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('connected Numbers retain bank identity and become unavailable on disconnect',()=>{const b=boot();b.click('person:sam');b.click('gallery');b.click('preview-module:external-monzo/current');b.click('pin-preview:external-monzo/current');const number=()=>b.d.querySelector('[data-module="external-monzo/current"]');assert.ok(number().querySelector('[data-bank=monzo]'));assert.match(number().textContent,/845/);b.click('connected-account:monzo/current');assert.deepEqual([...b.d.querySelectorAll('[data-container-section]')].map(x=>x.dataset.containerSection),['balance','actions','rules','activity']);b.click('disconnect-review:monzo');b.click('disconnect-confirm:monzo');assert.match(number().textContent,/Disconnected/);assert.doesNotMatch(number().textContent,/845/);b.click('undo');assert.match(number().textContent,/845/);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('agreement bottom sheet preserves the underlying pot, scroll, context and focus',()=>{const b=boot();b.click('person:elena');b.w.atlas.detail('fam');const sheet=b.d.querySelector('.sheet'),body=sheet.querySelector('.sheet-body'),card=b.d.querySelector('[data-action="container-how:fam"]'),message=b.d.querySelector('.support-message').textContent;body.scrollTop=160;card.focus();b.click('container-how:fam');b.click('container-agreement:fam');assert.match(b.d.querySelector('.agreement-sheet').textContent,/4.5% AER variable/);assert.match(b.d.querySelector('.agreement-sheet').textContent,/Each member/);assert.equal(b.d.querySelector('#overlay').inert,true);assert.equal(b.d.querySelector('.sheet'),sheet);b.d.dispatchEvent(new b.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(b.d.querySelector('#agreement-layer'),null);assert.equal(b.d.querySelector('#overlay').inert,false);assert.equal(body.scrollTop,160);assert.equal(b.d.activeElement,card);assert.equal(b.d.querySelector('.support-message').textContent,message);b.click('container-agreement:fam');b.d.querySelector('.agreement-scrim').click();assert.equal(b.d.querySelector('#agreement-layer'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('pause, cancel, remove and manual fulfilment preserve one agreement',()=>{const b=boot('workbench');b.click('bench-container:savings');const r='r-house-payday';b.click('condition-method:house/contribution');b.click('container-rule:'+r);b.click('container-rule-toggle:'+r);assert.match(b.d.querySelector('.method-overview').textContent,/manually/);b.click('close');assert.match(b.d.querySelector('.sheet-body .rule-detail-status').textContent,/Running/);b.click('container-rule-remove:'+r);b.click('container-rule-confirm');assert.match(how(b).querySelector('[data-condition=contribution]').textContent,/Your action/);b.click('condition-pay:house/contribution');assert.equal(b.d.querySelector('[name=amount]').value,'320');b.click('transfer-review');b.click('transfer-confirm');assert.match(how(b).querySelector('[data-condition=contribution]').textContent,/Complete/);assert.match(b.d.querySelector('.arrangement-benefit').textContent,/5.1%/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('global pause preserves current benefit and discloses manual responsibility',()=>{const b=boot('workbench');b.click('bench-container:savings');b.w.atlas.closeAll();b.click('tab:you');b.click('autonomy');assert.match(b.d.querySelector('[data-benefit-impact=house]').textContent,/manually/);b.click('pause-all');b.w.atlas.detail('house');assert.match(how(b).querySelector('[data-condition=contribution]').textContent,/Your action/);assert.match(b.d.querySelector('.arrangement-benefit').textContent,/5.1%/);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('merchant choice is reviewed, cancellable and does not count as earned cashback',()=>{const b=boot('workbench');b.click('bench-container:budget');const initial=b.d.querySelector('.detail-number').textContent;b.click('condition-merchant:budget');b.click('condition-merchant-review:budget');b.click('close');b.w.atlas.closeAll();b.w.atlas.detail('budget');assert.match(how(b).querySelector('[data-condition=merchant]').textContent,/Your choice/);b.click('condition-merchant:budget');b.click('condition-merchant-review:budget');b.click('condition-choice-confirm');assert.match(how(b).querySelector('[data-condition=merchant]').textContent,/Tesco.*Selected/);assert.equal(b.d.querySelector('.detail-number').textContent,initial);assert.match(how(b).querySelector('[data-condition=funding]').textContent,/£0 of £220/);assert.deepEqual(b.errors,[]);b.dom.window.close();});
test('lock requires consent and blocks withdrawal in the real transfer flow',()=>{const b=boot('workbench');b.click('bench-container:lock');b.click('condition-lock:house');b.click('condition-choice-confirm');assert.match(b.d.querySelector('#toast').textContent,/understand the lock/);b.d.querySelector('#lock-consent').checked=true;b.click('condition-choice-confirm');assert.match(how(b).querySelector('[data-condition=lock]').textContent,/Locked/);assert.match(b.d.querySelector('.arrangement-benefit').textContent,/4.6%/);b.click('transfer-from:house');b.d.querySelector('[name=to]').value='ac-cur';b.d.querySelector('[name=amount]').value='10';b.click('transfer-review');assert.match(b.d.querySelector('#toast').textContent,/locked/);assert.deepEqual(b.errors,[]);b.dom.window.close();});

test('Jordan cashback recovery uses reviewed manual payment and leaves September benefit unchanged',()=>{
 const b=boot();b.click('person:jordan');b.w.atlas.detail('grocery-wallet');
 assert.match(b.d.querySelector('.arrangement-benefit').textContent,/0% cashback/);b.click('agreement-recovery:grocery-wallet');
 assert.match(b.d.querySelector('.recovery-detail').textContent,/£220 of the £320/);
 b.click('condition-pay:grocery-wallet/funding');assert.equal(b.d.querySelector('#transfer-form [name=amount]').value,'100');
 b.click('transfer-review');b.click('transfer-confirm');
 assert.match(how(b).querySelector('.arrangement-recovery').textContent,/Ready for cashback to return/);
 assert.match(b.d.querySelector('.arrangement-benefit').textContent,/0% cashback/);
 b.click('support:discuss');assert.match(b.d.querySelector('.chat-thread').textContent,/earlier cashback is safe/);
 b.click('chat-chip:'+encodeURIComponent('Can I pay manually?'));assert.match(b.d.querySelector('.chat-thread').textContent,/September’s contribution is complete/);
 assert.deepEqual(b.errors,[]);b.dom.window.close();
});
test('grocery insight and money pot link both ways without looking like the same number',()=>{
 const b=boot();b.click('person:jordan');b.w.atlas.pin('grocery');b.click('module:grocery');
 assert.match(b.d.querySelector('.sheet-body').textContent,/£212.40/);assert.match(b.d.querySelector('.insight-link').textContent,/£69.70 left to spend/);
 b.click('pot:grocery-wallet');assert.match(b.d.querySelector('.container-value-label').textContent,/Left to spend/);
 b.click('module:grocery');assert.match(b.d.querySelector('#dialog-title').textContent,/Grocery spending/);
 assert.deepEqual(b.errors,[]);b.dom.window.close();
});
test('shared household review entries and Jordan card repayment work through the shared components',()=>{
 const b=boot('workbench');for(const id of ['flat','family','familySaving']){b.click('bench-container:'+id);assert.ok(b.d.querySelector('.container-members'));b.w.atlas.closeAll();}
 b.click('person:jordan');b.click('account:ac-cc');assert.match(how(b).querySelector('[data-condition=card-payment]').textContent,/Complete/);
 b.click('transfer-to:ac-cc');b.d.querySelector('#transfer-form [name=amount]').value='50';b.click('transfer-review');b.click('transfer-confirm');
 b.w.atlas.collect();b.click('account:ac-cc');assert.match(b.d.querySelector('.detail-number').textContent,/730/);
 assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('agreement overview progressively discloses conditions without hiding the benefit change',()=>{
 const b=boot();b.click('person:jordan');b.w.atlas.detail('grocery-wallet');
 const card=b.d.querySelector('.arrangement-disclosure');assert.equal(b.d.querySelector('#agreement-layer'),null);assert.equal(card.dataset.status,'attention');
 const summary=card;assert.match(summary.textContent,/Benefit changed/);assert.match(summary.textContent,/0% cashback/);assert.match(summary.textContent,/£100 short/);assert.doesNotMatch(summary.textContent,/Automate|Shop at|Spend within/);
 summary.click();assert.equal(b.d.querySelectorAll('#agreement-layer').length,1);assert.equal(b.d.querySelector('.how-sheet details'),null);assert.equal(b.d.querySelectorAll('.how-sheet [data-condition]').length,3);b.click('condition-pay:grocery-wallet/funding');assert.equal(b.d.querySelector('[name=amount]').value,'100');assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('compact arrangement distinguishes active rules, global pause and payment evidence',()=>{
 const b=boot();b.click('person:sam');b.w.atlas.detail('house');
 const line=()=>b.d.querySelector('.arrangement-rule-summary').textContent;
 assert.match(line(),/1 active rule/);assert.equal(b.d.querySelector('#agreement-layer'),null);
 b.w.atlas.closeAll();b.click('tab:you');b.click('autonomy');b.click('pause-all');b.w.atlas.detail('house');
 assert.match(line(),/1 rule · all paused globally/);assert.match(b.d.querySelector('.arrangement-benefit').textContent,/5.1%/);
 assert.match(how(b).querySelector('[data-condition=contribution]').textContent,/Your action/);
 assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('pot More shares Now customisation while keeping selections scoped to each container',()=>{
 const b=boot();b.click('person:sam');b.w.atlas.detail('house');b.click('container-more:house');
 assert.match(b.d.querySelector('.shortcut-editor').textContent,/On this pot/);assert.ok(b.d.querySelector('.available-actions [data-action="container-rule-new:house"]'));
 b.click('quick-edit');b.click('quick-select:rule');b.click('quick-select:info');b.click('quick-done');
 assert.ok(b.d.querySelector('.container-actions [data-action="container-rule-new:house"]'));assert.equal(b.d.querySelector('.container-actions [data-action="container-info:house"]'),null);
 b.click('container-more:house');assert.ok(b.d.querySelector('.available-actions [data-action="container-info:house"]'));b.click('quick-edit');b.click('quick-select:rule');b.click('quick-place:available');b.click('quick-done');
 assert.equal(b.d.querySelector('.container-actions [data-action="container-rule-new:house"]'),null);
 b.w.atlas.closeAll();b.w.atlas.detail('ef');assert.ok(b.d.querySelector('.container-actions [data-action="container-info:ef"]'));
 b.w.atlas.closeAll();b.click('quick-more');assert.match(b.d.querySelector('.shortcut-editor').textContent,/On your Now tab/);assert.ok(b.d.querySelector('.primary-actions [data-action=pay]'));
 b.w.atlas.closeAll();b.w.atlas.detail('house');b.click('container-more:house');b.click('container-rule-new:house');assert.ok(b.d.querySelector('#container-rule-form'));
 assert.deepEqual(b.errors,[]);b.dom.window.close();
});
test('credit More offers repayment and applicable actions; cancelling edits preserves shortcuts',()=>{
 const b=boot();b.click('person:jordan');b.click('account:ac-cc');b.click('container-more:ac-cc');
 assert.match(b.d.querySelector('.shortcut-editor').textContent,/On this account/);assert.ok(b.d.querySelector('[data-action="transfer-to:ac-cc"]'));assert.equal(b.d.querySelector('[data-action="transfer-from:ac-cc"]'),null);assert.equal(b.d.querySelector('[data-action="container-members:ac-cc"]'),null);
 b.click('quick-edit');b.click('quick-select:rule');b.click('quick-select:info');b.w.atlas.closeAll();b.click('account:ac-cc');
 assert.ok(b.d.querySelector('.container-actions [data-action="container-info:ac-cc"]'));assert.equal(b.d.querySelector('.container-actions [data-action="container-rule-new:ac-cc"]'),null);assert.deepEqual(b.errors,[]);b.dom.window.close();
});

test('how sheet terms and follow-up task return preserve overview scroll with one sheet',()=>{
 const b=boot();b.click('person:sam');b.w.atlas.detail('house');b.click('container-how:house');
 b.d.querySelector('.agreement-sheet-body').scrollTop=120;b.click('container-agreement:house');assert.equal(b.d.querySelectorAll('#agreement-layer').length,1);assert.ok(b.d.querySelector('.agreement-full'));
 b.click('container-how:house');assert.equal(b.d.querySelector('.agreement-sheet-body').scrollTop,120);assert.equal(b.d.querySelector('.how-sheet details'),null);
 b.click('condition-method:house/contribution');assert.equal(b.d.querySelector('#agreement-layer'),null);assert.ok(b.d.querySelector('.method-overview'));b.click('close');assert.ok(b.d.querySelector('.how-sheet'));assert.equal(b.d.querySelector('.agreement-sheet-body').scrollTop,120);
 b.click('agreement-close');assert.equal(b.d.querySelector('#agreement-layer'),null);assert.equal(b.d.querySelector('#overlay').inert,false);assert.deepEqual(b.errors,[]);b.dom.window.close();
});
