// Illustrative challenges and fixed bonus Points. Status qualification remains TRB-only.
export const challenges = [
  {
    id: 'in-touch',
    title: '30 days in touch',
    category: 'Find your rhythm',
    points: 100,
    target: 30,
    unit: 'daily reviews',
    cadence: 'day',
    duration: '30 days',
    motif: 'sun',
    color: 'amber',
    shape: 'scallop',
    description: 'A little attention, every day. Review your money on 30 different days.',
    commitment:
      'About a minute a day. Notice one payment, balance or upcoming bill — opening the app alone does not count.',
    step: 'I reviewed my money and noticed one thing today.',
    recovery: 'Miss a day? Your completed days stay. Pick up where you left off.',
  },
  {
    id: 'growing-savings',
    title: 'The growing saver',
    category: 'Build your savings',
    points: 200,
    target: 30,
    unit: 'saving days',
    cadence: 'day',
    duration: '30 saving days',
    motif: 'stairs',
    color: 'green',
    shape: 'shield',
    description: 'Start with £1. Add £1 to the amount you save each day, finishing with £30.',
    commitment:
      '£465 in total. Day 1: £1. Day 15: £15. Day 30: £30. The final seven days need £189, so check the whole challenge fits your budget.',
    step: 'I put aside today’s amount from money I can afford to save.',
    recovery:
      'Pause whenever you need. Resume at the next amount, without catching up missed days.',
    financial: true,
    schedule: 'ramp',
  },
  {
    id: 'little-often',
    title: 'Small change, big start',
    category: 'Build your savings',
    points: 100,
    target: 30,
    unit: 'saving days',
    cadence: 'day',
    duration: '30 saving days',
    motif: 'sprout',
    color: 'mint',
    shape: 'arch',
    description: 'Put aside £1 on 30 different days. Finish with £30 of your own.',
    commitment: '£1 each saving day, £30 altogether. A gentler alternative to The growing saver.',
    step: 'I saved £1 today, with essentials covered.',
    recovery: 'Keep every day you complete. Continue when £1 feels manageable.',
    financial: true,
  },
  {
    id: 'payday-first',
    title: 'Pay yourself first',
    category: 'Build your savings',
    points: 120,
    target: 3,
    unit: 'paydays',
    cadence: 'month',
    duration: '3 monthly paydays',
    motif: 'flags',
    color: 'blue',
    shape: 'hex',
    description: 'Make room for your future on three monthly paydays.',
    commitment:
      'Choose an affordable saving amount each payday, after allowing for bills and essentials. There is no minimum amount.',
    step: 'I set aside an affordable amount from this month’s pay.',
    recovery: 'A tight month can wait. Completed paydays still count.',
    financial: true,
  },
  {
    id: 'buffer-builder',
    title: 'A little breathing room',
    category: 'Build your savings',
    points: 150,
    target: 5,
    unit: 'saving weeks',
    cadence: 'week',
    duration: '5 weeks',
    motif: 'umbrella',
    color: 'lilac',
    shape: 'scallop',
    description: 'Build a £100 cushion, £20 at a time.',
    commitment: '£20 in five separate weeks. Keep it somewhere accessible for unexpected costs.',
    step: 'I added £20 to my accessible savings this week.',
    recovery: 'If you need the money, use it. You keep credit for the saving habit.',
    financial: true,
  },
  {
    id: 'goal-getter',
    title: 'First hundred',
    category: 'Build your savings',
    points: 150,
    target: 10,
    unit: 'saving weeks',
    cadence: 'week',
    duration: '10 weeks',
    motif: 'mountain',
    color: 'coral',
    shape: 'shield',
    description: 'Give one goal its first £100, with £10 a week.',
    commitment: 'Choose something that matters to you. Ten affordable £10 contributions make £100.',
    step: 'I added £10 towards my chosen goal this week.',
    recovery: 'Your progress stays if you skip a week or change your goal.',
    financial: true,
  },
  {
    id: 'spare-change',
    title: 'The leftover club',
    category: 'Build your savings',
    points: 120,
    target: 12,
    unit: 'weekly sweeps',
    cadence: 'week',
    duration: '12 weeks',
    motif: 'jar',
    color: 'amber',
    shape: 'arch',
    description: 'Give money left in your weekly budget a new purpose.',
    commitment:
      'Check upcoming costs first. Move only an affordable leftover amount to savings; there is no minimum.',
    step: 'I checked next week’s costs and saved an affordable leftover amount.',
    recovery: 'Nothing left this week? Skip it. There is no need to spend less on essentials.',
    financial: true,
  },
  {
    id: 'pause-purchase',
    title: 'The 48-hour pause',
    category: 'Spend with intention',
    points: 100,
    target: 10,
    unit: 'considered choices',
    cadence: 'day',
    duration: '10 purchases considered',
    motif: 'hourglass',
    color: 'lilac',
    shape: 'hex',
    description: 'Give ten non-essential purchases two days of thought.',
    commitment:
      'Wait 48 hours before deciding. Buying it or leaving it both count — the achievement is making an intentional choice.',
    step: 'I waited at least 48 hours, then decided on a non-essential purchase.',
    recovery: 'Take as long as you need. Never delay something essential.',
  },
  {
    id: 'cupboard-creative',
    title: 'Cupboard creative',
    category: 'Spend with intention',
    points: 80,
    target: 7,
    unit: 'creative meals',
    cadence: 'day',
    duration: '7 different days',
    motif: 'bowl',
    color: 'coral',
    shape: 'scallop',
    description: 'Make seven meals that use something you already have.',
    commitment:
      'Use an ingredient from your cupboard, fridge or freezer. You can buy extras; this is about using what you have.',
    step: 'I made a meal using an ingredient I already had.',
    recovery: 'No consecutive-day requirement. Collect your seven meals at your own pace.',
  },
  {
    id: 'spending-detective',
    title: 'Spending detective',
    category: 'Spend with intention',
    points: 80,
    target: 4,
    unit: 'weekly reviews',
    cadence: 'week',
    duration: '4 weeks',
    motif: 'magnifier',
    color: 'blue',
    shape: 'arch',
    description: 'Find the story behind your spending over four weeks.',
    commitment:
      'Each week, review three payments. Identify one that felt worthwhile and one you would think about differently.',
    step: 'I reviewed three payments and reflected on what mattered to me.',
    recovery: 'Missed a week? Continue next week.',
  },
  {
    id: 'subscription-sleuth',
    title: 'Keep, change or cancel',
    category: 'Spend with intention',
    points: 80,
    target: 3,
    unit: 'subscriptions reviewed',
    cadence: 'week',
    duration: '3 weeks',
    motif: 'tickets',
    color: 'mint',
    shape: 'shield',
    description: 'Give three subscriptions a proper value check.',
    commitment:
      'Review a different subscription each week: cost, next renewal and how much you use it. Keeping a useful service counts too.',
    step: 'I reviewed a different subscription and decided to keep, change or cancel it.',
    recovery: 'No cancellation target. The goal is knowing what you pay for.',
  },
  {
    id: 'budget-rhythm',
    title: 'In your own rhythm',
    category: 'Find your rhythm',
    points: 120,
    target: 4,
    unit: 'budget reviews',
    cadence: 'week',
    duration: '4 weeks',
    motif: 'wave',
    color: 'teal',
    shape: 'scallop',
    description: 'Keep your budget connected to real life for four weeks.',
    commitment:
      'Check what remains and what is coming up. Adjust your plan when life changes; spending the least is not the goal.',
    step: 'I reviewed my weekly budget and adjusted it where needed.',
    recovery: 'An overspend does not end the challenge. Reviewing and responding is what counts.',
  },
  {
    id: 'money-date',
    title: 'Better together',
    category: 'Look ahead',
    points: 150,
    target: 4,
    unit: 'money conversations',
    cadence: 'month',
    duration: '4 months',
    motif: 'orbit',
    color: 'rose',
    shape: 'hex',
    description: 'Make space for four honest conversations about money.',
    commitment:
      'Once a month, talk with someone you trust about one shared concern or goal. Agree one next step. Sharing account access is never required.',
    step: 'We talked about money and agreed one next step this month.',
    recovery: 'Choose who, how and when. You do not need to record private details.',
  },
  {
    id: 'future-letter',
    title: 'Dear future me',
    category: 'Look ahead',
    points: 100,
    target: 3,
    unit: 'monthly reflections',
    cadence: 'month',
    duration: '3 months',
    motif: 'envelope',
    color: 'blue',
    shape: 'arch',
    description: 'Choose a money goal, then keep coming back to why it matters.',
    commitment:
      'First month: write a short note to your future self. Next two months: revisit it and choose one realistic next step.',
    step: 'I wrote or revisited my future-self note and chose a next step.',
    recovery: 'Your goal can change. That is part of the reflection.',
  },
  {
    id: 'rainy-day-ready',
    title: 'Ready for a rainy day',
    category: 'Look ahead',
    points: 100,
    target: 4,
    unit: 'planning steps',
    cadence: 'week',
    duration: '4 weeks',
    motif: 'cloud',
    color: 'teal',
    shape: 'shield',
    description: 'Build a practical plan for an unexpected cost.',
    commitment: 'One small planning step a week. No minimum balance needed.',
    steps: [
      'List the essentials you would need to cover.',
      'Find out which savings you can access quickly.',
      'Choose who you would contact if money became tight.',
      'Write down your first steps for an unexpected bill.',
    ],
    recovery: 'You can pause between steps and return when you are ready.',
  },
  {
    id: 'scam-spotter',
    title: 'Keep your guard up',
    category: 'Grow your confidence',
    points: 80,
    target: 5,
    unit: 'practice days',
    cadence: 'day',
    duration: '5 days',
    motif: 'shield',
    color: 'green',
    shape: 'hex',
    description: 'Practise spotting pressure before you act on a money request.',
    commitment:
      'Take a few minutes on five different days. Use a made-up example; do not engage with a suspected scam.',
    steps: [
      'Find a sample message that creates urgency. Name the pressure tactic.',
      'Find a sample request to move money. List how you would independently verify it.',
      'Practise finding a company’s contact details without using a message link.',
      'Explain to someone you trust when you would stop and check a request.',
      'Write your own short pause-and-check routine.',
    ],
    recovery: 'Complete the practice days at your own pace.',
  },
  {
    id: 'interest-explorer',
    title: 'Make interest click',
    category: 'Grow your confidence',
    points: 100,
    target: 4,
    unit: 'learning weeks',
    cadence: 'week',
    duration: '4 weeks',
    motif: 'spiral',
    color: 'amber',
    shape: 'scallop',
    description: 'Put time into understanding the numbers behind a rate.',
    commitment:
      'Use examples rather than buying a product. Spend a little time learning each week, then explain the idea in your own words.',
    steps: [
      'Work through a simple-interest savings example.',
      'Compare it with a compound-interest example over the same time.',
      'Read the rate and fee information for an account you already have.',
      'Explain how changing a rate, fee or time period changes the example.',
    ],
    recovery: 'There is no quiz score to chase. Return to any idea you want to understand better.',
  },
  {
    id: 'investment-curious',
    title: 'Before the first step',
    category: 'Grow your confidence',
    points: 100,
    target: 4,
    unit: 'learning weeks',
    cadence: 'week',
    duration: '4 weeks',
    motif: 'compass',
    color: 'lilac',
    shape: 'arch',
    description: 'Explore investing before deciding whether it is right for you.',
    commitment: 'No investment required. Learning and deciding to wait is a valid outcome.',
    steps: [
      'Write down your goal, timeframe and when you might need the money.',
      'Explore a loss scenario and how you would feel about it.',
      'Compare how fees and diversification affect an example investment.',
      'Decide what you still need to understand or discuss with a qualified adviser.',
    ],
    recovery: 'You earn the badge for reflection, whatever you decide.',
  },
  {
    id: 'steady-investor',
    title: 'The patient investor',
    category: 'Grow your confidence',
    points: 200,
    target: 6,
    unit: 'months completed',
    cadence: 'month',
    duration: '6 months',
    motif: 'planet',
    color: 'blue',
    shape: 'hex',
    description: 'Check in with an existing £100 investment over six months.',
    commitment:
      'For money already invested and suitable for your circumstances. No top-ups or return target. Values can fall; six months is a check-in milestone, not a suggested time to sell.',
    step: 'I completed another month and reviewed my existing investment against my plan.',
    recovery:
      'If your circumstances change, pause or leave. Never stay invested just to earn Points.',
    financial: true,
    mature: true,
  },
  {
    id: 'debt-down',
    title: 'Keep your promise',
    category: 'Look ahead',
    points: 200,
    target: 6,
    unit: 'monthly repayments',
    cadence: 'month',
    duration: '6 months',
    motif: 'bridge',
    color: 'coral',
    shape: 'shield',
    description: 'Follow your agreed repayment plan for six months.',
    commitment:
      'Make the payment already agreed for each month. There is no extra payment requirement and no reward for taking on new borrowing.',
    step: 'I made this month’s agreed repayment.',
    recovery:
      'If a payment becomes difficult, contact your lender to discuss support. Your completed months stay.',
    financial: true,
  },
];
export const categories = [...new Set(challenges.map((b) => b.category))];
